name: Script Test

on:
  push:
    branches:
      - main

jobs:
  centos:
    runs-on: ubuntu-latest
    container: centos:8
    steps:
      - uses: actions/checkout@v4
      - name: Run script on CentOS
        run: |
          chmod +x ./tools/install.sh
          sh -c "./tools/install.sh"

  debian:
    runs-on: ubuntu-latest
    container: debian:12.5

    steps:
      - uses: actions/checkout@v4
      - name: Run script on Debian
        run: |
          chmod +x ./tools/install.sh
          sh -c "./tools/install.sh"