name: Script Test

on:
  push:
    branches:
      - main

jobs:
  centos:
    runs-on: ubuntu-latest
    container: centos:8
    steps:
      - uses: actions/checkout@v4
      - name: Run script test
        run: |
          chmod +x ./tools/install.sh
          sh -c "./tools/install.sh"

  debian:
    runs-on: ubuntu-latest
    container: debian:12.5
    steps:
      - uses: actions/checkout@v4
      - name: Run script test
        run: |
          chmod +x ./tools/install.sh
          sh -c "./tools/install.sh"

  ubuntu-20_04:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - uses: actions/checkout@v4
      - name: Run script test
        run: |
          chmod +x ./tools/install.sh
          sh -c "./tools/install.sh"

  ubuntu-22_04:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run script test
        run: |
          chmod +x ./tools/install.sh
          sh -c "./tools/install.sh"