name: Script Test

on:
  push:
    branches:
      - main

jobs:
  script-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Check files
#        run: |
#          ls -la
#          ls -la ./tools

      - name: Run script test
        run: |
          chmod +x ./tools/install.sh
          sh -c "./tools/install.sh"